language: go

go:
  - 1.9.x
  - 1.10.x

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
