# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/urfave/cli"
  version = "v1.19.1"
  
[[constraint]]
  name = "github.com/streadway/amqp"
  revision = "8e4aba63da9fc5571e01c6a45dc809a58cbc5a68"

[prune]
  go-tests = true
  unused-packages = true
